name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时运行一次
  workflow_dispatch:  # 支持手动触发

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Seed123-psy
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update snake animation"
          branch: main
          file_pattern: dist/*.svg
